# Base configuration
title: "Comarandr's Notes"
theme: jekyll-theme-cayman
markdown: kramdown
highlighter: rouge
permalink: pretty

collections:
  pages:
    output: true
    permalink: /:path/








# Style Variables
brand_color: "#DA253B"