title: Appunti
description: Raccolta di appunti vari
theme: minima
markdown: kramdown
mermaid: true
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge 
  syntax_highlighter_opts: 
    disable: false


  



